export const SET_CANDIDATES = 'SET_CANDIDATES';
export const SET_SELECTED_PAGE = 'SET_SELECTED_PAGE';
export const SET_CHOICE_WITH_PHOTO = 'SET_CHOICE_WITH_PHOTO';

export const SET_SHOW_FILTERS = 'SET_SHOW_FILTERS';
